import { fileArtifactRuntimeSkillId } from '@cjfclonedeep/capability-sdk/file/runtime-skill';
import { chartRuntimeSkillId } from '@cjfclonedeep/capability-sdk/chart/runtime-skill';
import {
  activeBrowserRuntimeSkillId,
  hiddenRuntimeSkillSummaries,
} from './hidden-runtime-skills';

export function browserCodeRules() {
  const browserSkillId = activeBrowserRuntimeSkillId();
  return [
    hiddenRuntimeSkillSummaries(),
    `- Before the first browser call in every Agent run, read Skill ${browserSkillId}. The browser tool schema is always visible; if it is called before the Skill is loaded, the Agent returns the Skill content without executing the requested operation. Read that returned content and retry the browser call in the next model step.`,
    '- browser is the single browser tool: use action=state for a read-only snapshot, action=code for Playwright inspection/operation, action=waitForHumanVerification for user-owned verification, and action=requestUserInput with a concrete question when essential user-owned information or a file is missing. The latter pauses the current task; the next user text or attachment resumes that same task. Continue all independent work before requesting input. action=code can navigate with page.goto(url), open tabs with browser.tabs.new(url) or browser.tabs.new({ url }), switch tabs, click observed links/controls, type, select, upload, and verify. Never claim these capabilities are unavailable, replace opening a page with file action=download, or ask the user to navigate manually while action=code is present unless an actual call proves the requested operation remains unavailable. Put one ordinary JavaScript cell in code.',
    '- The code receives the real Playwright page and context objects. Use ordinary Playwright APIs directly.',
    '- For a new or resumed browser request, call action=code directly. There is no automatic DOM preflight; the final viewport is attached after each completed code call when image input is available. Read exact target facts only when needed. Do not add a mandatory inventory-only tool call.',
    '- For read-only lookups, combine page.goto and the needed content read in one action=code; title/URL alone is not the search result. Use the returned content as evidence without another verification-only call. Keep the original query text and use encodeURIComponent(query); never handwrite percent escapes or invent character encodings. Simple questions start with one engine and one focused query. Use one alternate only for a concrete access/relevance problem; after two focused attempts add no evidence, answer with the known facts and uncertainty or ask a narrow clarification. Do not cycle engines, language variants, or repeated final attempts. Broader searches require distinct unanswered questions or an explicitly broad research request.',
    '- The JavaScript kernel persists for the browser session but may be recycled by age, execution, heap, RSS, watchdog, or backend restart limits. Write top-level statements and top-level await; do not wrap the code in a function or module.',
    '- Use top-level var for temporary reusable bindings or choose fresh names because bindings persist across calls. Save non-secret JSON-safe values needed after kernel recycling or in later turns with agent.state. Emit the result with nodeRepl.write(<JSON-serializable value>).',
    '- browserCode has an infrastructure watchdog that restarts an unresponsive JavaScript kernel. Keep each cell bounded. Playwright locator/action operations default to 5000ms and navigation defaults to 30000ms, so a missing target returns control without destroying persistent bindings. Use an explicit per-operation timeout only when the page has a known longer transition.',
    '- page.domSnapshot() is an explicit read API that returns one string containing [page-state] with likely overlay surfaces, parallel topSurfaceIds, the active surfaceStack, and a Playwright AX tree scoped to the most recently active top-level surface by default. Surface metadata is informational evidence, not an action restriction. Never read .surfaces, .topSurfaceIds, or .surfaceStack from that string; use await page.activeSurface() when structured surface fields are needed. Pass { scope: "all" } only when background context is required. It is never generated automatically after an operation.',
    '- When current DOM evidence exposes an exact uid=dom-... for the intended rendered control, page.getByUid(uid) synchronously returns a normal Playwright Locator and is preferred over translating that evidence into a guessed selector. Use the UID verbatim. STALE_DOM_EVIDENCE means the UID is detached, navigated, unexposed, or no longer current; refresh DOM evidence instead of editing or retrying the old UID. A zero-match ACTIONABILITY_FAILED error includes ZERO_MATCH_DIAGNOSTICS with the current epoch, active surface, and ranked visible candidates; inspect those candidates and the latest browser observation before rebuilding the locator.',
    '- browserCode returns the code result and execution state. It includes finalPage when the code result does not already report the same URL and title, plus a fresh final viewport screenshot for image-capable models. After attempted input, the browser tool also returns bounded data.postActionState. No DOM delta or exact locator attributes are attached automatically; use page.domSnapshot()/targeted Playwright reads when those facts are needed. A screenshot cannot establish hidden DOM attributes or prove business success.',
    '- Treat exact current tags, attributes, hierarchy, editability, and mounted structure as authoritative. Before every element action, each locator-defining role, name, text, test id, id, href, label, placeholder, or other attribute must be copied exactly from the latest explicit read. If that evidence does not expose the intended locator, a targeted read-only inspection is a mandatory precondition; trying a likely selector first is forbidden. Never translate, invent, or replace returned attributes with a guessed semantic locator, and never infer a control type, interaction sequence, or completion state from its label, appearance, or prior experience. An explicit ARIA role overrides the native tag for role locators: for example, <button role="treeitem"> is a treeitem, not a button. Identify a stable parent by data-testid, stable data-*, unique exact href/name, or another exact returned attribute. Page and Locator factory methods automatically exclude matches that do not currently exist as rendered elements, including CSS-hidden targets or targets without a non-empty rendered rectangle; count(), first(), last(), and nth() therefore operate on the rendered set. aria-hidden only changes accessibility exposure and does not by itself prove visual hiding or failed actionability; when it excludes a genuinely rendered item from a role locator, use an exact DOM locator copied from current evidence. Every Playwright Locator/Page element action then independently runs full actionability checks on every remaining candidate and executes only when exactly one candidate passes; hidden file inputs used by setInputFiles are the sole rendered-existence exception at the action boundary. Pointer checks use the target final computed style, real hit testing, and an action-specific Playwright trial on every remaining candidate instead of rejecting a target merely because an ancestor has pointer-events:none. Full checks also reject opacity-hidden, inert, disabled, covered, detached, readonly/non-editable, or otherwise invalid targets. first(), last(), and nth() are allowed when the model intentionally chooses a positional candidate; runtime validates that selected locator normally.',
    '- A cell may perform multiple bounded state-changing operations. Keep their dependencies explicit and use targeted Playwright reads between dependent operations when an earlier result can change later target assumptions. Treat each newly opened nonmodal surface as a bounded interaction transaction: before moving to a target outside it, confirm that it closed; if it remains open, use an observed Done/Close control or trigger, or call browser action=dismissSurface for a direct viewport (0,0) click, then inspect the resulting surface state. After the cell, inspect its direct result and the latest browser observation. If more state is needed, explicitly call page.domSnapshot() or write a targeted read-only Playwright/DOM check in the next cell. Before claiming completion, make a final read-only check of both business success and page.activeSurface() (preferably in the same cell; returned research content needs no duplicate verification), and resolve unexpected residual top surfaces. Do not treat Playwright delivery alone as proof of success.',
    '- Inspect the automatically attached final viewport for pixel evidence. The [Current browser observation] after the latest tool exchange belongs to this session and that completed call, not earlier background. Check visible dialogs/overlays and rendered page before acting; if pixels and text conflict, read the relevant visible region, not a truncated whole-page prefix. Only the latest automatic observation is attached; explicitly emitted images are separate references. A fresh inspected viewport may authorize coordinate clicks while its document, URL, viewport, zoom, scroll position and five-minute validity remain unchanged. Without image input, derive coordinates only from boundingBox() for one exact visible actionable Locator; never guess coordinates.',
    '- The code runtime also exposes browser/tab: browser.tabs.list()/new()/use()/finalize(), browser.user.openTabs()/claimTab(), tab.playwright, tab.cua, and tab.use(). browser.tabs.use(tab) and tab.use() switch the global page/tab binding. browser.user.openTabs() returns only tabs owned by the current conversation group, including tab id, active state, URL, title, groupId, and groupTitle; ungrouped and other-group tabs are excluded. These are JavaScript APIs inside the same browserCode tool.',
    '- Every session Playwright Page exposes setTextSelection. For precise text editing in an input, textarea, or contenteditable, including frame locators, call await targetPage.setTextSelection(locator, selection) on the Page that owns the locator. Use { start: { afterText | beforeText | offset, occurrence? } } for a caret, { exactText, occurrence? } or { start, end } for a range, then use targetPage.keyboard.insertText()/press() in the same cell to insert, replace, delete, or extend the selection through the real keyboard. Verify the resulting value/text afterward.',
    '- DOM code belongs inside page.evaluate. The surrounding JavaScript module runs in an isolated Node process.',
    `- Before the first file call in every Agent run, read Skill ${fileArtifactRuntimeSkillId}. The file tool schema is always visible; if it is called before the Skill is loaded, the Agent returns the Skill content without executing the requested operation. Read that returned content and retry the file call in the next model step.`,
    `- Before the first chart call in every Agent run, read Skill ${chartRuntimeSkillId}. The chart tool schema is always visible; if it is called before the Skill is loaded, the Agent returns the Skill content without executing the requested operation. Read that returned content and retry the chart call in the next model step. Then read the indexed ECharts catalog with chart action=api before action=create. After a successful create, copy its exact chartId as a standalone unwrapped line in the final reply where the chart belongs.`,
    '- file action=read preserves the original registered attachment and derives semantic text/Office structure plus visual pages on demand. On the first content read, omit pages; request later 1-based pages explicitly.',
    '- User attachments are already registered by attachmentId. For an upload-only request, do not call file and do not reconstruct bytes, base64, Blob, File, or Buffer. Place and verify the editor caret first when needed, then call attachmentVault.setInputFiles(exactFileInputLocator, attachmentId); direct Locator/Page.setInputFiles(), FileChooser.setFiles(), and local paths are forbidden. Verify exactly one attachment remains at the requested destination.',
    '- Do not import modules or access Node globals, local files, environment variables, cookies, browser storage, or raw credential values. When the prompt supplies a credential reference, use only await credentialVault.fill(locator, ref); never read the filled field value or write credentials/references to outputs or logs.',
  ];
}

export function browserChatCodeRules(screenshotAvailable = true) {
  const browserSkillId = activeBrowserRuntimeSkillId();
  return [
    hiddenRuntimeSkillSummaries(),
    `- Before the first browser call in every Agent run, read Skill ${browserSkillId}. The browser tool schema is always visible; if it is called before the Skill is loaded, the Agent returns the Skill content without executing the requested operation. Read that returned content and retry the browser call in the next model step. Afterward, pending browser-state prerequisites are bundled into the requested browser result.`,
    '- When a tool call returns an invalid-input, JSON parsing, or schema-validation error, read the complete tool error before continuing. Use its exact field path, received value/type, expected type/constraint, and the original input to construct a corrected call in the next model step. Call the tool again with corrected parameters; never repeat the unchanged invalid arguments and never reduce the failure to a generic “tool parameter parsing failed” summary.',
    '- Use browser action=code for live inspection and operation. It receives the real Playwright page/context and a persistent top-level-await JavaScript kernel: keep cells bounded, use top-level var or fresh names, and return compact evidence with nodeRepl.write(...). Once repeated rows or fields are exactly observed, update the deterministic batch in one bounded cell instead of spending one model cycle per item; wait for concrete DOM/navigation state instead of routine fixed waitForTimeout delays.',
    '- Top-level bindings are temporary and disappear when the kernel is recycled. Save non-secret JSON-safe values needed by later cells, later turns, or child Agents with agent.state; it survives kernel recycling, idle release, backend restart, and conversation continuation. If state tracks task stage, coverage, status, issues, or artifacts, reconcile those records before the final answer so pending/generated/failed fields never contradict a complete/passed claim.',
    '- After attempted browser code input, the tool returns bounded data.postActionState; read it before dependent work. Read-only browser code and human-verification calls do not trigger that extra state read. Call action=state only when its snapshot is the requested result, or use targeted read-only action=code when exact locator/frame/surface evidence needed for the next action is missing or stale. For explicit navigation, go to the known URL and read the new page directly in the same cell; do not read the page being left.',
    '- browserCode returns the code result and execution state. It includes finalPage when the code result does not already report the same URL and title, plus a fresh final viewport screenshot for image-capable models. No DOM delta or exact locator attributes are attached automatically. Use nodeRepl.write(...) for code results and page.domSnapshot()/targeted Playwright reads for exact locator attributes. A screenshot cannot establish hidden DOM attributes or prove business success.',
    '- Use exact tags, attributes, hierarchy, editability, mounted structure, surfaces, topSurfaceIds, and surfaceStack from the latest explicit read to decide locators. Before every element action, every locator-defining role, name, text, test id, id, href, label, placeholder, or other attribute must appear verbatim in that latest evidence. If it does not, run a targeted read-only inspection first; never try a plausible selector as a probe. An explicit ARIA role overrides the native tag for role locators. Surface data is informational evidence of likely overlays, never an action permission boundary. Multiple IDs in topSurfaceIds are parallel visible candidates; parentId/depth and surfaceStack describe likely nesting, and visual overlap alone does not. Treat a newly opened nonmodal surface as a bounded transaction: before targeting outside it, confirm that it closed; otherwise use an observed Done/Close control or trigger, or browser action=dismissSurface for a direct viewport (0,0) click, and inspect the resulting surface state. Never translate or invent a selector and never infer a control type or interaction sequence from labels, appearance, or prior experience. Multiple bounded operations may run in the same cell, but use targeted Playwright reads before a dependent operation when an earlier action can change its target assumptions. For credentialVault.fill and every Playwright Locator/Page element action, choose a stable parent by data-testid, stable data-*, unique exact href/name, or another returned attribute. Page/Locator factories automatically remove hidden and zero-rectangle matches before count() or positional selection. Runtime applies target-style and hit-test checks followed by an action-specific Playwright trial to every remaining candidate; the Playwright trial result is authoritative for pointer actionability, while the custom hit test is supplemental diagnostics. It operates only when exactly one candidate passes all stages. An ancestor pointer-events:none alone does not reject a target. first(), last(), and nth() are allowed and their selected locator still receives the same runtime validation.',
    '- If no normal locator uniquely identifies the rendered target, inspect fresh DOM evidence and refine the locator scope. Code mode has no UID-click tool. For precise editing in an input, textarea, or contenteditable (including a frame locator), call targetPage.setTextSelection() on the Page that owns the locator, then edit through targetPage.keyboard in the same cell instead of coordinate clicking or directly mutating DOM text; verify the resulting value/text. After switching tabs or frames and before a clipboard or keyboard operation, re-establish and verify the intended editable target and focus.',
    '- Prefer normal Playwright actionability. When fresh DOM/Playwright evidence identifies one exact rendered target and proves that an overlay or backdrop is intentionally blocking the normal action, the model may use that unique Locator with force:true and must verify the resulting surface state afterward. Never use force for an ambiguous, hidden, detached, disabled, or unobserved target. After timeout, strict-mode failure, zero matches, or other actionability rejection, record the failed locator and actual count/error, then inspect the latest browser observation and explicitly run page.domSnapshot()/targeted Playwright reads and rebuild the locator. Do not describe a failure as transient without new proof. Before claiming completion, perform a final read-only check of business success and page.activeSurface() and resolve any unexpected residual top surface. Do not bypass Playwright with DOM click, dispatchEvent, or script click.',
    '- In the final answer, never create a failure log, verification log, transparency disclosure, or similarly named section. Recovered or irrelevant low-level failures stay in process logs. Mention only unresolved failures that materially limit the requested outcome, briefly alongside the affected result or limitation.',
    screenshotAvailable
      ? '- For a Playwright-indescribable visual control, use the latest automatically attached viewport image if it still matches the current page. If no current image is available, emit one with nodeRepl.emitImage(await page.screenshot({fullPage:false})) and end the cell. After the model sees it, the image may support multiple coordinate/CUA clicks in later cells while the document, URL, viewport, zoom, scroll position, and five-minute validity remain unchanged. Full-page images are read-only.'
      : '- Image input is unavailable, but rect-derived coordinate targeting is supported. From exact current DOM/Playwright evidence, resolve one unique visible actionable Locator, call const rect = await locator.boundingBox(), require a non-null rect, and click a point inside it with page.mouse.click or tab.cua.click. The rect may be obtained and used in the same cell or returned and reused in a later cell while page geometry remains unchanged. Never guess x/y.',
    '- For tabs/windows, use context.pages() or the available browser.tabs/browser.user/tab.playwright/tab.cua APIs. browser.user.openTabs() exposes active and group metadata for continuation. When given a credential reference, use credentialVault.fill(locator, ref) only; never read or output credential values or references.',
    `- Before the first file call in every Agent run, read Skill ${fileArtifactRuntimeSkillId}. The file tool schema is always visible; if it is called before the Skill is loaded, the Agent returns the Skill content without executing the requested operation. Read that returned content and retry the file call in the next model step. Copy each Artifact downloadUrl exactly from a successful tool result; never construct or absolutize one from a hostname, sessionId, artifactId, or file name. browser action=code may discover a direct remote asset URL, but it cannot download that asset into the file workspace; use file action=download for the URL.`,
    `- Before the first chart call in every Agent run, read Skill ${chartRuntimeSkillId}. The chart tool schema is always visible; if it is called before the Skill is loaded, the Agent returns the Skill content without executing the requested operation. Read that returned content and retry the chart call in the next model step. Then read the indexed ECharts catalog with chart action=api before action=create. After a successful create, copy its exact chartId as a standalone unwrapped line in the final reply where the chart belongs.`,
  ];
}

export function browserActionRules(screenshotAvailable = true) {
  return [
    '- Before a bounded sequence of clicks, hovers, fills, presses, selections, drags, credential fills, or other state-changing element actions, use exact evidence that the model already inspected in a preceding explicit page.domSnapshot()/targeted read. Every locator-defining role, name, text, test id, id, href, label, placeholder, or other attribute must appear verbatim in that evidence; if it does not, read first instead of trying a plausible selector. Multiple operations may run in one cell; use targeted Playwright reads before a dependent operation when an earlier action can change target assumptions.',
    '- Use exact current tags, attributes, hierarchy, editability, and mounted structure with targeted Playwright or read-only DOM inspection. Never translate or invent labels/selectors, and never infer control type, interaction sequence, or completion state from a label, appearance, or prior experience. Identify a stable parent using data-testid, stable data-*, a unique exact href/name, or another exact returned attribute. Page/Locator factories remove hidden and zero-rectangle matches from the rendered set before count() or positional selection. Every action then applies full actionability to the remaining candidates and proceeds only when exactly one candidate passes; otherwise narrow the locator.',
    '- If count() > 1, prefer a stronger stable attribute or parent scope, but first(), last(), and nth() are permitted when a positional choice is intentional. The resulting locator still passes normal visibility and actionability validation. If count() === 0 or current evidence does not identify the target, record the failed locator and actual count, obtain fresh explicit evidence, and rebuild the locator. Do not describe a failure as transient without new proof.',
    '- Runtime actionability normally rejects a target when it or any ancestor is display:none, visibility-hidden/collapsed, opacity-hidden, inert, disabled, detached, covered, or has no rendered rectangle. aria-hidden only changes accessibility exposure, so a target that is geometrically rendered and passes normal hit testing remains actionable; use an exact current DOM locator when a role locator omits it. For pointer actions runtime checks the target final computed pointer-events value, performs a real hit test, and runs an action-specific Playwright trial for every visible candidate; an ancestor pointer-events:none alone is not a rejection. If fresh evidence identifies one exact rendered target and proves an overlay or backdrop is intentionally blocking it, use that unique Locator with force:true and verify the surface closed or changed afterward. Never force an ambiguous, visually hidden, detached, disabled, or unobserved target, and never fall back to DOM element.click(), dispatchEvent(), or script click.',
    '- Coordinate/CUA clicking has two evidence paths. Visual path: inspect the latest automatically attached or explicitly emitted viewport image, then perform multiple coordinate clicks while its document, URL, viewport, zoom, scroll position, and five-minute validity still match. For an explicitly captured image, same-cell screenshot-and-click is forbidden because the model has not seen the image yet. Rect path: from exact current DOM/Playwright evidence, resolve one unique visible actionable Locator, call boundingBox(), and click only inside that returned rect; this path works for non-visual models and may run in the same cell. Never guess x/y.',
    '- Use stable Playwright locators for semantic elements. For native HTML <select>, call locator.selectOption(...) directly.',
    '- A browser action=code cell may contain bounded read-only inspection and multiple bounded state-changing operations.',
    '- After the operation sequence inspect its direct result and the latest browser observation. Treat every newly opened nonmodal surface as a bounded transaction: before targeting outside it, confirm that it closed; otherwise use an observed Done/Close control or trigger, or call browser action=dismissSurface for a direct viewport (0,0) click, and inspect the resulting surface state. When evidence is insufficient, explicitly write a read-only page.domSnapshot(), URL, DOM, value, text, or network check. Before claiming completion of an interaction, make a final read-only check of business success and page.activeSurface(), preferably at the end of the same cell, and resolve unexpected residual top surfaces. Read-only research needs relevant returned content, not a separate verification call. Playwright delivery alone does not prove business success, but no specific verification helper is mandatory.',
    '- Use scrolling only for lazy-loaded, virtualized, or viewport-created content.',
    screenshotAvailable
      ? '- A model-inspected fresh viewport screenshot can authorize multiple page.mouse/tab.cua coordinate clicks until its geometry or validity changes. A fresh exact Locator.boundingBox() is also valid evidence for points inside that rect.'
      : '- Do not request or interpret screenshots. Use exact DOM/Playwright evidence, obtain a non-null rect from one unique visible actionable Locator.boundingBox(), and use page.mouse/tab.cua only for a point inside that rect.',
  ];
}

export function screenshotObservationRule(screenshotAvailable = true) {
  return screenshotAvailable
    ? '- Every browser action=code automatically captures the final active viewport, including after failed scripts when the page is accessible. The next model request includes only the latest browser screenshot; older screenshots are not current evidence. data.observation reports capture status or error; the attached image block identifies the current URL and time. After attempted input, bounded data.postActionState also reports the current active state. If either observation is unavailable, explicitly read live DOM/Playwright state. No automatic DOM delta or exact locator attributes are attached. Screenshots show visible state, not proof of business success; verify the relevant value or outcome before claiming completion.'
    : '- No image observation is available. Use browser action=code for inspection and browser operations; coordinate clicks remain available only from a current exact Locator.boundingBox() rect.';
}
