import type { CapabilitySkill } from '../index.ts';
export const novelRuntimeSkill = Object.freeze({
  id: 'system-novel-runtime', title: 'Novel Runtime',
  summary: '<system_skill id="system-novel-runtime"><title>小说创作</title><description>直接编辑同一小说实体，每次保存同步返回修改内容与校验结果，由当前模型迭代完善。</description></system_skill>',
  required: true, activation: [{ toolName: 'novel' }],
  content: `# Novel Runtime

1. YOU are the author and editor. There is NO independent reviewer model and no review action. Tools store the novel, apply edits, and run deterministic checks. Judge plot, timeline, character motivation, facts, continuity and style yourself using the user's requirements and the actual saved text.
2. A novel is ONE persistent entity shared by all the user's conversations: plan contains idea, outline, timeline, background, characters, style and ordered chapter outlines; chapters contains the written prose plus summary/continuity. First call plan with the complete shape: {"action":"plan","reason":"保存大纲草稿","plan":{"title":"书名","idea":"点子","outline":"含结局的大纲","timeline":[{"time":"第一天","event":"事件"}],"background":"世界背景","characters":[{"name":"角色名","role":"角色定位","description":"人物介绍"}],"style":"视角、语言与节奏，字符串","chapters":[{"title":"章节名","summary":"本章安排"}]}}. Extra fields are ignored, required fields/types are validated. Save immediately, retain projectId/revision, and reuse that identity for all later changes.
3. Iterate directly: read the saved draft when needed -> judge what needs changing -> call edit -> inspect the synchronous changes and validation -> continue substantive edits UNTIL YOU judge that no further changes are needed for the requested scope. Every successful write returns exact canonical changes with path, before, after and existence flags, plus the latest revision and local validation. These changes are already saved: do not apply them twice. No fixed revision quota exists. A clean validation report is NOT a semantic or literary approval; it cannot check whether a character's motivation or a plot reversal is convincing. Do not keep calling validate or submitting unchanged edits without a concrete reason.
4. Example edit: {"action":"edit","reason":"修正第三章时间线","projectId":"returned id","expectedRevision":1,"edits":[{"op":"replace","path":"/plan/chapters/2/summary","value":"完整的新章节摘要"}]}. JSON Pointer indexes are zero-based; replace changes an existing field, add inserts an array item (/- appends), remove deletes it. Edit plan fields and existing /chapters/0/content, title, summary, continuity. Make related corrections in one atomic call; preserve unchanged text and human edits. The returned content is complete for changed fields, not a shortened preview. On conflict, read and reconcile the latest revision. Invalid patches save NOTHING; correct the offending paths/values and resubmit the related changes together. Do not recreate the book or resend the full plan for small corrections.
5. Every plan/edit/writeChapter runs local structure, chapter sequence, phrase-rule and stale-context checks and returns validation. Structural/input errors reject the mutation atomically; content/phrase warnings remain attached to the saved draft so you can repair it directly. Use validate(projectId, expectedRevision) to recheck a saved entity without changing it. Address concrete problems through edit; assess warnings in context. Avoid stock phrases such as 命运的齿轮开始转动、石子落入心湖泛起涟漪、嘴角勾起一抹邪魅的笑、而他们的故事才刚刚开始; use actions, dialogue and specific imagery instead. Do not send the manuscript to another review model or create a hidden review/resubmission loop.
6. Present the resulting outline. If actual prose is requested, call confirmPlan with the current revision and wait for explicit user confirmation of that stored version. Never invent approval; a pure outline request can finish with the saved outline. Plan changes invalidate earlier confirmation. After confirmation, writeChapter saves the next chapter or revises the latest chapter. Required shape: {"action":"writeChapter","reason":"保存第一章","projectId":"returned id","expectedRevision":2,"chapter":{"number":1,"title":"章节名","content":"完整章节正文","summary":"本章摘要","continuity":"本章确立的事实、人物变化与未解线索"}}. All five chapter fields are required; number is 1-based and belongs inside chapter. Use the actual latest revision returned by confirmation/read/write, not the example value or planVersion. A matching top-level chapterNumber is tolerated, but conflicting numbers are rejected. The tool returns saved text changes and local checks immediately, without an AI review. Continue checking and directly editing as in step 3. Earlier written chapters can be edited through edit; retain their established facts and human revisions.
7. list locates existing books across conversations. read returns the complete plan, chapter index and latest three summaries/continuity records; chapterNumber reads one entire written chapter. Keep full manuscript text in the entity. After context compression, recover by projectId and read needed chapters rather than regenerate successful writes. contextStale means the old summary/continuity may be inaccurate; inspect complete prose and submit BOTH summary and continuity when synchronizing chapter context. A chapter created under an older planVersion needs your consistency judgment, not another reviewer.
8. export returns manuscript and plan links with confirmation/progress labels. Deliver exact returned URLs. Respect the requested writing scope; do not claim an unfinished novel is complete. Finish when the requested content is saved and you judge no further substantive change is needed, then explain any unresolved points honestly.`,
} satisfies CapabilitySkill);
